name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        name: 'Build and Push'
        runs-on: ${{ matrix.os }}
        outputs:
          docker_tag: ${{ steps.generate_tag.outputs.sha }}

        strategy:
            matrix:
                node-version: [18, 20, 22]
                os: [ubuntu-latest]
                # os: [ubuntu-latest, windows-latest, macos-latest]
        
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            
            - name: Setup NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            
            - name: Install dependencies
              run: yarn
            
            - name: Running Tests
              run: yarn test

            - name: Generate Tag
              id: generate_tag
              run: |
                  SHA=$(echo $GITHUB_SHA | head -c7)
                  echo "sha=$SHA" >> $GITHUB_OUTPUT

            - name: Login into the Container Registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build Docker Image
              run: docker build -t jlss14/aula_docker_devops:${{ steps.generate_tag.outputs.sha }} .

            - name: Push Docker Image to DockerHub
              run: docker push jlss14/aula_docker_devops:${{ steps.generate_tag.outputs.sha }}

            - name: Build Docker Image
              run: docker build -t aula-ci-cd:latest .
    
    deploy:
      name: Deploy on Digital Ocean
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Copy docker-compose file via ssh
          uses: appleboy/scp-action@v0.1.7
        with:
          hust: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "./docker-compose.yaml"
          target: "~/"

        - name: Deploy to Digital Ocean droplet via SSH action
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            password: ${{ secrets.PASSWORD }}
            envs: GITHUB_SHA
            script: |
              # Extract the ltag on job build
              TAG=${{ needs.build.outputs.docker_tag }}
              # Ceate env file
              [ -e .env ] && rm .env
              touch .env
              echo "DOCKER_IMAGE_TAG=$TAG" > .env
              # Login Docker
              docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
              # Remove Old Containers
              CONTAINERS=${docker ps -a -q}
              if [ -n "$CONTAINERS" ]; then
                docker rm $CONTAINERS
              else
                echo " No containers to remove"
              fi
              # Run a new container from a new image
              docker-compose up -d